# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:15.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i
      - run: echo $targetDate
      - run: node ut.js $userID $password $targetDate $code
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy