# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: 
          name: install puppeteer
          command: npm i puppeteer
      - run: 
          name: run test
          command: node response.js

workflows:
  Puppeteer Test:
    jobs:
    - test
  version: 2