# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: 
          name: install puppeteer
          command: npm i puppeteer
      - run: 
          name: run test
          command: node ut.js $userID $password $targetDate $code

workflows:
  Puppeteer Test:
    jobs:
    - test
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only: test
 